CPP=g++ -std=c++11
CPPFLAGS=-O3 -Wall -DVERBOSE
INCLUDES=-I./include/
SOURCES=./include/BasicCDS.cpp binarySearch.cpp

unary:
	@echo " [BLD] Binary Searches...."
	@$(CPP) $(CPPFLAGS) $(INCLUDES) $(SOURCES) -o bSearch
